plugins {
    id 'net.minecraftforge.gradle' version '5.1.+'
    id 'maven-publish'
}

group = 'com.mimic.monster'
version = '1.0.0'
archivesBaseName = 'monstermod'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'

    runs {
        client {
            workingDirectory project.file('run')
            property 'mixin.env.disableRefMap', 'false'
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            jvmArgs '-Dgeckolib.debug_renderers=true'
        }
    }
}

repositories {
    maven { url = 'https://maven.minecraftforge.net/' }
    maven { url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/' }
    maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
}

dependencies {
    minecraft "net.minecraftforge:forge:1.20.1-47.2.0"
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    implementation fg.deobf('org.spongepowered:mixin:0.8.5')
    implementation fg.deobf('software.bernie.geckolib:geckolib-forge-1.20.1:4.4.9')
}

jar {
    manifest {
        attributes([
                "MixinConfigs": "monstermod.mixins.json"
        ])
    }
}

sourceSets.main.resources {
    srcDir 'src/main/resources'
    exclude '**/*.cache'
}

tasks.processResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE

    inputs.property "version", project.version
    inputs.property "mcversion", '1.20.1'

    from(sourceSets.main.resources.srcDirs) {
        include 'META-INF/mods.toml'
        expand(
                'mod_id': archivesBaseName,
                'mod_version': version,
                'minecraft_version': '1.20.1'
        )
    }
    from(sourceSets.main.resources.srcDirs) {
        exclude 'META-INF/mods.toml'
    }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}