import org.gradle.api.file.DuplicatesStrategy

plugins {
    id 'net.minecraftforge.gradle' version '5.1.+'
    id 'org.spongepowered.mixin' version '0.7.+'
    id 'maven-publish'
    id 'eclipse'
}

println "forge_version_range = ${forge_version_range}"

group = mod_group_id
version = mod_version
archivesBaseName = mod_id

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'

    runs {
        client {
            workingDirectory project.file('run')
            property 'mixin.env.disableRefMap', 'true'
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                monstermod {
                    source sourceSets.main
                }
            }
        }
    }
}

mixin {
    add sourceSets.main, "monstermod.refmap.json"
    config "monstermod.mixins.json"
}

repositories {
    maven { url = 'https://maven.minecraftforge.net/' }
    maven { url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/' }
    maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    implementation fg.deobf('software.bernie.geckolib:geckolib-forge-1.20.1:4.7.1.2')
}

jar {
    manifest {
        attributes([
                "MixinConfigs": "monstermod.mixins.json"
        ])
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
    exclude '**/*.cache'
}
tasks.processResources {
    // このタスクの入力プロパティとしてバージョンを含めることで、
    // バージョンが変更されたときにタスクが再実行されることを保証します。
    duplicatesStrategy = DuplicatesStrategy.INCLUDE

    inputs.property "version", project.version
    inputs.property "mcversion", minecraft_version // minecraft_versionも追加

    // sourceSets.main.resources.srcDirs からリソースを取得
    from(sourceSets.main.resources.srcDirs) {
        // META-INF/mods.toml ファイルのみをフィルタリング対象とします
        include 'META-INF/mods.toml'

        expand(
                properties + [
                        'mod_id': mod_id,
                        'mod_name': mod_name,
                        'mod_license': mod_license,
                        'mod_version': mod_version,
                        'mod_group_id': mod_group_id,
                        'mod_authors': mod_authors,
                        'mod_description': mod_description,
                        'minecraft_version': minecraft_version,
                        'forge_version': forge_version,
                        'forge_version_range': forge_version_range,
                        'minecraft_version_range': minecraft_version_range
                ]
        )
    }
    from(sourceSets.main.resources.srcDirs) {
        exclude 'META-INF/mods.toml' // mods.tomlは上記で既に処理されているため、ここでは除外
    }
}

// tasks.withType(JavaCompile) はこのままでOK
tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}